name: join_asvbins
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.*
  - pandas
  - pytest
  - scikit-bio
  - scipy==1.8.1
  - mmseqs2!=10.6d92c
  - barrnap
  - blast
  - samtools==1.11
  - snakemake-minimal
  - pip
  - pip:
    - join_asvbins
