name: join_asvbins
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.*
  - pandas
  - pytest
  - scikit-bio
  - mmseqs2!=10.6d92c
  - barrnap
  - snakemake-minimal
  - pip:
    - join_asvbins
